# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/byrhn"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/mondefetch"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "pinterest"
name = "Pinterest"
url = "https://pinterest.com/mondefetch"
[social.params]
icon = "brand-pinterest"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://instagram.com/mondefetch"
[social.params]
icon = "brand-instagram"

[[social]]
identifier = "facebook"
name = "Facebook"
url = "https://facebook.com/mondefetch"
[social.params]
icon = "brand-facebook"